services:
  - type: web
    name: dollar-decoded-ffmpeg
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PEXELS_API_KEY
        sync: false
