services:
  - type: web
    name: dollar-decoded-ffmpeg
    runtime: python
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: t5Ffyw3tZsmu43O2ACmjtt1oI8ukKjlqAjk9OZ74bEebaDfwH8KQB1zK
        sync: false
